name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "app/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: innovaker/zmk-build-arm:2.3
    strategy:
      matrix:
        board:
          - bluemicro840_v1
          - nice_nano
          - nrfmicro_13
          - proton_c
        shield:
          - boardsource3x4
          - corne_left
          - corne_right
          - iris_left
          - iris_right
          - jian_left
          - jian_right
          - jorne_left
          - jorne_right
          - kyria_left
          - kyria_right
          - lily58_left
          - lily58_right
          - nibble
          - quefrency_left
          - quefrency_right
          - reviung41
          - romac
          - romac_plus
          - settings_reset
        include:
          - board: proton_c
            shield: clueboard_california
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: 4-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            4-${{ runner.os }}-build-${{ env.cache-name }}-
            4-${{ runner.os }}-build-
            4-${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: West init
        run: west init -l app
      - name: West update
        run: west update
      - name: West config Zephyr base
        run: west config --global zephyr.base-prefer configfile
      - name: West Zephyr export
        run: west zephyr-export
      - name: West build
        run: west build -s app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.board }}-${{ matrix.shield }}-zmk-uf2"
          path: build/zephyr/zmk.uf2
